import { Metadata } from "next";
import "../globals.css";
import Context from "../context/Context";
import { Public_Sans } from "next/font/google";
import { SideBar } from "../components/__organism";

const ps = Public_Sans({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ps.className} antialiased w-full h-full relative flex flex-col items-start`}
      >
        <div className=" w-full bg-[#F8F4F0]">
          <Context>
            <SideBar />
            {children}
          </Context>
        </div>
      </body>
    </html>
  );
}
