// import type { Metadata } from "next";
// import "./globals.css";
// import Context from "./context/Context";
// import { Public_Sans, Barlow, Work_Sans } from "next/font/google";

// const ps = Public_Sans({ subsets: ["latin"], weight: ["400", "700"] });
// const barlow = Barlow({ subsets: ["latin"], weight: ["400"] });
// const ws = Work_Sans({ subsets: ["latin"], weight: ["700"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${ps.className} antialiased`}>
//         <Context>{children}</Context>
//       </body>
//     </html>
//   );
// }

// import type { Metadata } from "next";
// import "./globals.css";
// import Context from "./context/Context";
// import { Public_Sans, Barlow, Work_Sans } from "next/font/google";
// import { SideBar } from "./components/__organism";

// const ps = Public_Sans({ subsets: ["latin"], weight: ["400", "700"] });
// const barlow = Barlow({ subsets: ["latin"], weight: ["400"] });
// const ws = Work_Sans({ subsets: ["latin"], weight: ["700"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${ps.className} antialiased`}>
//         <section className="w-full h-full min-h-screen  grid grid-cols-1 lg:grid-cols-[20.83%_1fr]">
//           {/* <div className="max-h-[52px] md:max-h-[74px]  lg:w-full lg:min-h-full h-screen  bg-[#201F24] lg:rounded-t-xl lg:rounded-tl-none lg:rounded-r-3xl order-last lg:order-none">
//             <SideBar />
//           </div> */}

//           <Context>{children}</Context>
//         </section>
//       </body>
//     </html>
//   );
// }

// import type { Metadata } from "next";
// import "./globals.css";
// import Context from "./context/Context";
// import { Public_Sans } from "next/font/google";
// import { SideBar } from "./components/__organism";
// // import { SideBar } from "./components/__organism";

// const ps = Public_Sans({ subsets: ["latin"], weight: ["400", "700"] });
// // const barlow = Barlow({ subsets: ["latin"], weight: ["400"] });
// // const ws = Work_Sans({ subsets: ["latin"], weight: ["700"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${ps.className} antialiased`}>
//         <section className="w-full h-full">
//           <section className="w-full h-full min-h-screen  grid grid-cols-1 lg:grid-cols-[20.83%_1fr]">
//             <div className="max-h-[52px] md:max-h-[74px]  lg:w-full lg:min-h-full h-screen  bg-[#201F24] lg:rounded-t-xl lg:rounded-tl-none lg:rounded-r-3xl order-last lg:order-none">
//               <SideBar />
//             </div>
//             <Context>{children}</Context>
//           </section>
//         </section>
//       </body>
//     </html>
//   );
// }

// import { Metadata } from "next";
// import "./globals.css";
// import Context from "./context/Context";
// import { Public_Sans } from "next/font/google";
// import { SideBar } from "./components/__organism"; // Import the Sidebar component

// const ps = Public_Sans({ subsets: ["latin"], weight: ["400", "700"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${ps.className} antialiased`}>
//         <section className="w-full h-full">
//           <section className="w-full h-full min-h-screen grid grid-cols-1 lg:grid-cols-[20.83%_1fr]">
//             {/* Render SideBar only for non-auth pages */}
//             <div className="max-h-[52px] md:max-h-[74px] lg:w-full lg:min-h-full h-screen bg-[#201F24] lg:rounded-t-xl lg:rounded-tl-none lg:rounded-r-3xl order-last lg:order-none">
//               <SideBar />
//             </div>
//             <Context>{children}</Context>
//           </section>
//         </section>
//       </body>
//     </html>
//   );
// }

















// import { Metadata } from "next";
// import "../globals.css";
// import Context from "../context/Context";
// import { Public_Sans } from "next/font/google";
// import { SideBar } from "../components/__organism"; 

// const ps = Public_Sans({ subsets: ["latin"], weight: ["400", "700"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${ps.className} antialiased`}>
//         <main className="w-full h-full">
//           <section className="w-full h-full min-h-screen grid grid-cols-1 lg:grid-cols-[20.83%_1fr]">
//             <div className="max-h-[52px] md:max-h-[74px] lg:w-full lg:min-h-full h-screen bg-[#201F24] lg:rounded-t-xl lg:rounded-tl-none lg:rounded-r-3xl order-last lg:order-none">
//               <SideBar />
//             </div>

//             <section className="w-full relative ">
//               <Context>{children}</Context>
//             </section>
//           </section>
//         </main>
//       </body>
//     </html>
//   );
// }







import { Metadata } from "next";
import "../globals.css";
import Context from "../context/Context";
import { Public_Sans } from "next/font/google";
import { SideBar } from "../components/__organism"; 

const ps = Public_Sans({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ps.className} antialiased`}>
        <main className="w-full h-full">
          <section className="w-full h-full min-h-screen relative bg-[#F2F3F7]">
            <div className="absolute z-10 left-0 top-0 max-h-[52px] md:max-h-[74px] lg:min-w-[300px] lg:min-h-full h-screen bg-[#201F24] lg:rounded-t-xl lg:rounded-tl-none lg:rounded-r-3xl order-last lg:order-none">
              <SideBar />
            </div>

            <section className="w-full pl-[300px] bg-[#F2F3F7]">
              <Context>{children}</Context>
            </section>
          </section>
        </main>
      </body>
    </html>
  );
}

