
// import { Metadata } from "next";
// import "../globals.css";
// import Context from "../context/Context";
// import { Public_Sans } from "next/font/google";
// import { SideBar } from "../components/__organism";

// const ps = Public_Sans({ subsets: ["latin"], weight: ["400", "700"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${ps.className} antialiased `}>
//         <main className="w-full h-full">
//           <section className="w-full h-full min-h-screen relative grid grid-cols-1 lg:grid-cols-[20.83%_1fr] bg-red-400">
//             <div className="absolute z-10 bottom-0 left-0 max-h-[52px] w-full md:max-h-[74px] lg:left-0 lg:top-0 lg:w-[300px] lg:min-h-full h-screen bg-[#201F24] lg:rounded-t-xl lg:rounded-tl-none lg:rounded-r-3xl order-last lg:order-none">
//               <SideBar />
//             </div>

//             <section className="w-full lg:pl-[300px] bg-[#F2F3F7] lg:w-[79.19%] ">
//               <Context>{children}</Context>
//             </section>
//           </section>
//         </main>
//       </body>
//     </html>
//   );
// }

import { Metadata } from "next";
import "../globals.css";
import Context from "../context/Context";
import { Public_Sans } from "next/font/google";
import { SideBar } from "../components/__organism";

const ps = Public_Sans({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${ps.className} antialiased w-full h-full relative grid grid-cols-1 lg:grid-cols-[20.83%_1fr]`}
        className={`${ps.className} antialiased w-full h-full relative flex flex-col items-start`}
      >
        {/* <div className="absolute z-10 bottom-0 left-0 max-h-[52px] w-full md:max-h-[74px] lg:left-0 lg:top-0 lg:w-[300px] lg:min-h-full h-screen bg-[#201F24] lg:rounded-t-xl lg:rounded-tl-none lg:rounded-r-3xl order-last lg:order-none">
          <SideBar />
        </div> */}

        {/* <SideBar /> */}

        {/* <div className="lg:pl-[300px] w-full bg-[#F8F4F0]"> */}
        <div className=" w-full bg-[#F8F4F0]">

            <Context>
            <SideBar />
              {children}</Context>
        </div>


      </body>
    </html>
  );
}
